# WormFS Storage Node Configuration
# This file contains the configuration settings for a WormFS storage node

# Unique identifier for this storage node
node_id: "550e8400-e29b-41d4-a716-446655440000"

# Path to the SQLite metadata database
metadata_db_path: "data/metadata.db"

# Networking configuration
networking:
  # Address to listen on for libp2p connections
  listen_address: "/ip4/0.0.0.0/tcp/4001"

# Storage configuration
storage_config:
  # OPTION 1: Single disk mode (backward compatibility)
  # Uncomment the line below for single-disk setup
  # storage_root: "data/chunks"
  
  # OPTION 2: Multi-disk mode (recommended for production)
  # Multi-disk configuration for enhanced reliability and performance
  disks:
    - disk_id: "primary"
      path: "data/chunks/disk1"
      min_free_space: 1073741824  # 1GB
    - disk_id: "secondary"
      path: "data/chunks/disk2"  
      min_free_space: 1073741824  # 1GB
    - disk_id: "tertiary"
      path: "data/chunks/disk3"
      min_free_space: 1073741824  # 1GB

# Disk monitoring configuration
disk_monitoring:
  # Interval between disk health checks (seconds)
  check_interval_seconds: 30
  # Number of consecutive failures before marking disk offline
  failure_threshold_consecutive: 3
  # Percentage of disk usage that triggers space alerts
  space_alert_threshold_percent: 90

# Chunk placement configuration
chunk_placement:
  # Minimum number of disks required for chunk placement
  min_disks_required: 1
  # Whether to prefer disks with more available space
  prefer_more_space: true
  # Maximum attempts to find placement before giving up
  max_placement_attempts: 10
  # Whether to allow degraded placement (fewer disks than chunks)
  allow_degraded_placement: false

# Erasure coding configuration
erasure_config:
  # Number of data shards (k)
  data_shards: 4
  # Number of parity shards (m) 
  parity_shards: 2
  # Target stripe size in bytes (1MB default)
  stripe_size: 1048576

# Maximum file size to accept (100GB default)
max_file_size: 107374182400

# Example configurations for different use cases:

# High redundancy (6+3):
# erasure_config:
#   data_shards: 6
#   parity_shards: 3
#   stripe_size: 2097152

# Low latency (8+4):
# erasure_config:
#   data_shards: 8
#   parity_shards: 4
#   stripe_size: 4194304

# Storage constrained (3+1):
# erasure_config:
#   data_shards: 3
#   parity_shards: 1
#   stripe_size: 524288
