//! # StorageEndpoint Component
//!
//! StorageEndpoint provides a gRPC API server for client and node-to-node communication.
//!
//! ## Responsibilities
//!
//! - Exposing gRPC APIs for FUSE filesystem clients
//! - Providing node-to-node APIs for chunk data transfer
//! - Providing node-to-node APIs for metadata snapshot transfer
//! - Routing filesystem requests to FileSystemService
//! - Routing chunk requests to FileStore
//! - Routing snapshot requests to SnapshotStore
//! - Implementing request authentication and authorization
//! - Managing connection lifecycle and health checks
//! - Providing request rate limiting and backpressure
//!
//! ## API Categories
//!
//! ### FUSE Filesystem APIs
//! These APIs are used by client FUSE filesystems to interact with WormFS:
//! - File operations (create, read, write, delete, rename)
//! - Directory operations (mkdir, rmdir, readdir)
//! - Metadata operations (getattr, setattr, chmod, chown)
//! - Lock operations (acquire, release, extend)
//!
//! ### Chunk Transfer APIs
//! These APIs are used by storage nodes to request chunk data:
//! - GetChunk: Retrieve a chunk by ID
//! - VerifyChunk: Check chunk integrity
//! - StreamChunks: Bulk chunk transfer
//!
//! ### Snapshot Transfer APIs
//! These APIs are used by storage nodes to catch up on metadata:
//! - GetLatestSnapshot: Retrieve the latest metadata snapshot
//! - GetSnapshotAtIndex: Retrieve a specific snapshot
//! - StreamSnapshot: Efficient snapshot transfer
//!
//! ## Request Routing
//!
//! ```text
//! Client Request
//!      │
//!      ▼
//! ┌─────────────────┐
//! │ StorageEndpoint │
//! └────────┬────────┘
//!          │
//!          ├─── FUSE API ────────────► FileSystemService
//!          │
//!          ├─── Chunk API ───────────► FileStore
//!          │
//!          └─── Snapshot API ────────► SnapshotStore
//! ```
//!
//! ## gRPC Service Definition
//!
//! The service is defined using Protocol Buffers and compiled with `tonic`.
//! See `proto/wormfs.proto` for the complete service definition.

pub mod types;

use async_trait::async_trait;
use std::net::SocketAddr;
pub use types::{EndpointConfig, EndpointError};

/// StorageEndpoint trait defines the interface for the gRPC API server.
///
/// Implementations provide gRPC endpoints for client and node-to-node communication.
#[async_trait]
#[cfg_attr(any(test, feature = "test-utils"), mockall::automock)]
pub trait StorageEndpoint: Send + Sync {
    /// Create a new StorageEndpoint.
    ///
    /// # Arguments
    ///
    /// * `config` - Configuration including listen address and TLS settings
    ///
    /// # Returns
    ///
    /// A new StorageEndpoint instance ready to serve requests.
    fn new(config: EndpointConfig) -> Result<Self, EndpointError>
    where
        Self: Sized;

    /// Start the gRPC server and begin serving requests.
    ///
    /// This method starts the gRPC server and blocks until shutdown is requested.
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - Server cannot bind to the listen address
    /// - TLS configuration is invalid
    /// - Server fails during operation
    async fn serve(&self) -> Result<(), EndpointError>;

    /// Gracefully shutdown the gRPC server.
    ///
    /// This method stops accepting new requests and waits for in-flight
    /// requests to complete before shutting down.
    ///
    /// # Arguments
    ///
    /// * `timeout` - Maximum time to wait for in-flight requests
    ///
    /// # Errors
    ///
    /// Returns an error if shutdown cannot complete within the timeout.
    async fn shutdown(&self, timeout: std::time::Duration) -> Result<(), EndpointError>;

    /// Get the address the server is listening on.
    ///
    /// # Returns
    ///
    /// The socket address the server is bound to.
    fn local_addr(&self) -> SocketAddr;

    /// Check if the server is currently serving requests.
    ///
    /// # Returns
    ///
    /// `true` if the server is active, `false` otherwise.
    fn is_serving(&self) -> bool;

    // ===== Direct Client Upload Operations =====
    //
    // These operations support direct client-to-storage-node chunk uploads,
    // bypassing the leader to avoid bottlenecks during write operations.
    //
    // Workflow:
    // 1. Leader generates time-limited upload token for each chunk
    // 2. Client receives tokens along with storage node addresses
    // 3. Client uploads chunks directly to storage nodes with tokens
    // 4. Storage nodes validate tokens before accepting uploads
    // 5. Storage nodes stage chunks on disk
    // 6. Leader commits metadata through Raft
    // 7. Storage nodes activate staged chunks

    /// Accept a chunk upload with time-limited token authentication.
    ///
    /// This method allows clients to upload chunk data directly to storage nodes
    /// without going through the leader. The upload token must be generated by
    /// the leader and is time-limited (typically 5-10 minutes).
    ///
    /// The chunk is written in a "staged" state and is not visible in the
    /// filesystem until the leader commits the metadata through Raft and the
    /// chunk is activated.
    ///
    /// # Arguments
    ///
    /// * `chunk_data` - Chunk data including header and payload
    /// * `token` - Time-limited upload token issued by the leader
    ///
    /// # Returns
    ///
    /// The ChunkId of the uploaded chunk.
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - Token is invalid or expired
    /// - Token is for a different chunk
    /// - Disk is full or unavailable
    /// - I/O errors occur during upload
    async fn upload_chunk(
        &self,
        chunk_data: crate::file_store::ChunkData,
        token: &str,
    ) -> Result<crate::file_store::ChunkId, EndpointError>;

    /// Generate a time-limited upload token for a chunk (leader only).
    ///
    /// This method should only be called by the leader node when coordinating
    /// a write operation. The token allows clients to upload the specified chunk
    /// directly to storage nodes without additional authentication.
    ///
    /// Tokens are currently implemented as simple hardcoded strings but will be
    /// replaced with public/private key-based tokens in the future.
    ///
    /// # Arguments
    ///
    /// * `chunk_id` - Identifier of the chunk this token is valid for
    /// * `valid_for` - How long the token should remain valid
    ///
    /// # Returns
    ///
    /// An upload token string that can be used to upload the specified chunk.
    fn generate_upload_token(
        &self,
        chunk_id: crate::file_store::ChunkId,
        valid_for: std::time::Duration,
    ) -> String;

    /// Validate an upload token for a chunk.
    ///
    /// This method checks whether a provided token is valid for uploading
    /// the specified chunk. Tokens must not be expired and must match the
    /// expected chunk ID.
    ///
    /// # Arguments
    ///
    /// * `chunk_id` - Identifier of the chunk being uploaded
    /// * `token` - Upload token to validate
    ///
    /// # Returns
    ///
    /// `true` if the token is valid for the specified chunk, `false` otherwise.
    fn validate_upload_token(&self, chunk_id: crate::file_store::ChunkId, token: &str) -> bool;
}
