//! Metadata Protocol Module
//!
//! This module provides the protocol buffer message definitions and conversion
//! utilities for the WormFS metadata gossip protocol (Phase 2B).
//!
//! The protocol enables distributed metadata synchronization across storage nodes
//! using a master-coordinated, eventually consistent approach.

use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};
use thiserror::Error;
use uuid::Uuid;

use crate::erasure_coding::ErasureCodingConfig;
use crate::metadata_store::{
    ChunkId, ChunkMetadata, FileMetadata, StorageLocation, StripeMetadata,
};

// Include generated protobuf code
// This will be generated by tonic-build in build.rs
include!(concat!(env!("OUT_DIR"), "/wormfs.rs"));

/// Current protocol version
pub const PROTOCOL_VERSION: (u32, u32, u32) = (1, 0, 0);

/// Errors that can occur during protocol operations
#[derive(Error, Debug)]
pub enum ProtocolError {
    #[error("Invalid UUID format: {0}")]
    InvalidUuid(String),

    #[error("Invalid timestamp: {0}")]
    InvalidTimestamp(String),

    #[error("Missing required field: {0}")]
    MissingField(String),

    #[error("Protocol version mismatch: expected {expected:?}, got {got:?}")]
    VersionMismatch {
        expected: (u32, u32, u32),
        got: (u32, u32, u32),
    },

    #[error("Invalid event type: expected event payload")]
    InvalidEventType,

    #[error("Serialization error: {0}")]
    Serialization(String),
}

pub type ProtocolResult<T> = Result<T, ProtocolError>;

// ============================================================================
// Helper Functions
// ============================================================================

/// Create a protocol version message
pub fn create_protocol_version() -> ProtocolVersion {
    ProtocolVersion {
        major: PROTOCOL_VERSION.0,
        minor: PROTOCOL_VERSION.1,
        patch: PROTOCOL_VERSION.2,
    }
}

/// Validate protocol version compatibility
pub fn validate_protocol_version(version: &ProtocolVersion) -> ProtocolResult<()> {
    let got = (version.major, version.minor, version.patch);

    // Major version must match exactly
    if got.0 != PROTOCOL_VERSION.0 {
        return Err(ProtocolError::VersionMismatch {
            expected: PROTOCOL_VERSION,
            got,
        });
    }

    Ok(())
}

/// Convert SystemTime to Unix timestamp (seconds)
pub fn system_time_to_timestamp(time: SystemTime) -> u64 {
    time.duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

/// Convert Unix timestamp to SystemTime
pub fn timestamp_to_system_time(timestamp: u64) -> SystemTime {
    UNIX_EPOCH + std::time::Duration::from_secs(timestamp)
}

// ============================================================================
// Conversion Functions: Domain Types -> Proto Types
// ============================================================================

/// Convert FileMetadata to FileInfo
impl From<&FileMetadata> for FileInfo {
    fn from(metadata: &FileMetadata) -> Self {
        FileInfo {
            file_id: metadata.file_id.to_string(),
            path: metadata.path.to_string_lossy().to_string(),
            size: metadata.size,
            permissions: metadata.permissions,
            created_at: system_time_to_timestamp(metadata.created_at),
            modified_at: system_time_to_timestamp(metadata.modified_at),
            accessed_at: system_time_to_timestamp(metadata.accessed_at),
            stripe_count: metadata.stripe_count,
            checksum: metadata.checksum,
        }
    }
}

/// Convert StripeMetadata to StripeInfo
impl From<&StripeMetadata> for StripeInfo {
    fn from(metadata: &StripeMetadata) -> Self {
        StripeInfo {
            file_id: metadata.file_id.to_string(),
            stripe_index: metadata.stripe_index,
            original_size: metadata.original_size as u64,
            chunk_count: metadata.chunk_count as u32,
            erasure_config: Some((&metadata.erasure_config).into()),
            created_at: system_time_to_timestamp(metadata.created_at),
        }
    }
}

/// Convert ChunkMetadata to ChunkInfo
impl From<&ChunkMetadata> for ChunkInfo {
    fn from(metadata: &ChunkMetadata) -> Self {
        ChunkInfo {
            file_id: metadata.file_id.to_string(),
            stripe_index: metadata.stripe_index,
            chunk_index: metadata.chunk_index as u32,
            size: metadata.size,
            checksum: metadata.checksum,
            storage_location: Some((&metadata.storage_location).into()),
            created_at: system_time_to_timestamp(metadata.created_at),
            last_verified: metadata.last_verified.map(system_time_to_timestamp),
        }
    }
}

/// Convert StorageLocation to StorageLocationInfo
impl From<&StorageLocation> for StorageLocationInfo {
    fn from(location: &StorageLocation) -> Self {
        StorageLocationInfo {
            node_id: location.node_id.to_string(),
            disk_id: location.disk_id.clone(),
            path: location.path.to_string_lossy().to_string(),
        }
    }
}

/// Convert ErasureCodingConfig to ErasureCodingConfigInfo
impl From<&ErasureCodingConfig> for ErasureCodingConfigInfo {
    fn from(config: &ErasureCodingConfig) -> Self {
        ErasureCodingConfigInfo {
            data_shards: config.data_shards as u32,
            parity_shards: config.parity_shards as u32,
            shard_size: config.shard_size() as u32,
        }
    }
}

// ============================================================================
// Conversion Functions: Proto Types -> Domain Types
// ============================================================================

/// Convert FileInfo to FileMetadata
impl TryFrom<&FileInfo> for FileMetadata {
    type Error = ProtocolError;

    fn try_from(info: &FileInfo) -> ProtocolResult<Self> {
        let file_id = Uuid::parse_str(&info.file_id)
            .map_err(|_| ProtocolError::InvalidUuid(info.file_id.clone()))?;

        Ok(FileMetadata {
            file_id,
            path: PathBuf::from(&info.path),
            size: info.size,
            permissions: info.permissions,
            created_at: timestamp_to_system_time(info.created_at),
            modified_at: timestamp_to_system_time(info.modified_at),
            accessed_at: timestamp_to_system_time(info.accessed_at),
            stripe_count: info.stripe_count,
            checksum: info.checksum,
        })
    }
}

/// Convert StripeInfo to StripeMetadata
impl TryFrom<&StripeInfo> for StripeMetadata {
    type Error = ProtocolError;

    fn try_from(info: &StripeInfo) -> ProtocolResult<Self> {
        let file_id = Uuid::parse_str(&info.file_id)
            .map_err(|_| ProtocolError::InvalidUuid(info.file_id.clone()))?;

        let erasure_config = info
            .erasure_config
            .as_ref()
            .ok_or_else(|| ProtocolError::MissingField("erasure_config".to_string()))?;

        let erasure_config = ErasureCodingConfig::new(
            erasure_config.data_shards as usize,
            erasure_config.parity_shards as usize,
            erasure_config.shard_size as usize,
        )
        .map_err(|e| ProtocolError::Serialization(e.to_string()))?;

        Ok(StripeMetadata {
            file_id,
            stripe_index: info.stripe_index,
            original_size: info.original_size as usize,
            chunk_count: info.chunk_count as u8,
            erasure_config,
            created_at: timestamp_to_system_time(info.created_at),
        })
    }
}

/// Convert ChunkInfo to ChunkMetadata
impl TryFrom<&ChunkInfo> for ChunkMetadata {
    type Error = ProtocolError;

    fn try_from(info: &ChunkInfo) -> ProtocolResult<Self> {
        let file_id = Uuid::parse_str(&info.file_id)
            .map_err(|_| ProtocolError::InvalidUuid(info.file_id.clone()))?;

        let storage_location = info
            .storage_location
            .as_ref()
            .ok_or_else(|| ProtocolError::MissingField("storage_location".to_string()))?;

        let storage_location = storage_location.try_into()?;

        Ok(ChunkMetadata {
            file_id,
            stripe_index: info.stripe_index,
            chunk_index: info.chunk_index as u8,
            size: info.size,
            checksum: info.checksum,
            storage_location,
            created_at: timestamp_to_system_time(info.created_at),
            last_verified: info.last_verified.map(timestamp_to_system_time),
        })
    }
}

/// Convert StorageLocationInfo to StorageLocation
impl TryFrom<&StorageLocationInfo> for StorageLocation {
    type Error = ProtocolError;

    fn try_from(info: &StorageLocationInfo) -> ProtocolResult<Self> {
        let node_id = Uuid::parse_str(&info.node_id)
            .map_err(|_| ProtocolError::InvalidUuid(info.node_id.clone()))?;

        Ok(StorageLocation {
            node_id,
            disk_id: info.disk_id.clone(),
            path: PathBuf::from(&info.path),
        })
    }
}

// ============================================================================
// Event Constructors
// ============================================================================

/// Create a FileCreated event
pub fn create_file_created_event(
    sequence_number: u64,
    originator_peer_id: String,
    originator_node_id: Uuid,
    file_metadata: &FileMetadata,
) -> MetadataEvent {
    MetadataEvent {
        version: Some(create_protocol_version()),
        sequence_number,
        originator: Some(MetadataPeerInfo {
            peer_id: originator_peer_id,
            node_id: originator_node_id.to_string(),
            timestamp: system_time_to_timestamp(SystemTime::now()),
        }),
        timestamp: system_time_to_timestamp(SystemTime::now()),
        event: Some(metadata_event::Event::FileCreated(FileCreatedEvent {
            file: Some(file_metadata.into()),
        })),
    }
}

/// Create a FileDeleted event
pub fn create_file_deleted_event(
    sequence_number: u64,
    originator_peer_id: String,
    originator_node_id: Uuid,
    file_id: Uuid,
    path: PathBuf,
) -> MetadataEvent {
    MetadataEvent {
        version: Some(create_protocol_version()),
        sequence_number,
        originator: Some(MetadataPeerInfo {
            peer_id: originator_peer_id,
            node_id: originator_node_id.to_string(),
            timestamp: system_time_to_timestamp(SystemTime::now()),
        }),
        timestamp: system_time_to_timestamp(SystemTime::now()),
        event: Some(metadata_event::Event::FileDeleted(FileDeletedEvent {
            file_id: file_id.to_string(),
            path: path.to_string_lossy().to_string(),
        })),
    }
}

/// Create a ChunkPlaced event
pub fn create_chunk_placed_event(
    sequence_number: u64,
    originator_peer_id: String,
    originator_node_id: Uuid,
    chunk_metadata: &ChunkMetadata,
) -> MetadataEvent {
    MetadataEvent {
        version: Some(create_protocol_version()),
        sequence_number,
        originator: Some(MetadataPeerInfo {
            peer_id: originator_peer_id,
            node_id: originator_node_id.to_string(),
            timestamp: system_time_to_timestamp(SystemTime::now()),
        }),
        timestamp: system_time_to_timestamp(SystemTime::now()),
        event: Some(metadata_event::Event::ChunkPlaced(ChunkPlacedEvent {
            chunk: Some(chunk_metadata.into()),
        })),
    }
}

/// Create a ChunkRemoved event
pub fn create_chunk_removed_event(
    sequence_number: u64,
    originator_peer_id: String,
    originator_node_id: Uuid,
    chunk_id: ChunkId,
    node_id: Uuid,
) -> MetadataEvent {
    MetadataEvent {
        version: Some(create_protocol_version()),
        sequence_number,
        originator: Some(MetadataPeerInfo {
            peer_id: originator_peer_id,
            node_id: originator_node_id.to_string(),
            timestamp: system_time_to_timestamp(SystemTime::now()),
        }),
        timestamp: system_time_to_timestamp(SystemTime::now()),
        event: Some(metadata_event::Event::ChunkRemoved(ChunkRemovedEvent {
            file_id: chunk_id.file_id.to_string(),
            stripe_index: chunk_id.stripe_index,
            chunk_index: chunk_id.chunk_index as u32,
            node_id: node_id.to_string(),
        })),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn test_protocol_version() {
        let version = create_protocol_version();
        assert_eq!(version.major, 1);
        assert_eq!(version.minor, 0);
        assert_eq!(version.patch, 0);

        // Valid version should pass
        assert!(validate_protocol_version(&version).is_ok());

        // Different major version should fail
        let bad_version = ProtocolVersion {
            major: 2,
            minor: 0,
            patch: 0,
        };
        assert!(validate_protocol_version(&bad_version).is_err());
    }

    #[test]
    fn test_time_conversion() {
        let now = SystemTime::now();
        let timestamp = system_time_to_timestamp(now);
        let converted = timestamp_to_system_time(timestamp);

        // Should be very close (within 1 second due to precision loss)
        let diff = now
            .duration_since(converted)
            .unwrap_or_else(|_| converted.duration_since(now).unwrap());
        assert!(diff.as_secs() <= 1);
    }

    #[test]
    fn test_file_metadata_conversion() {
        let original = FileMetadata::new(PathBuf::from("/test/file.txt"), 1024, 0o644);

        // Convert to proto
        let proto: FileInfo = (&original).into();
        assert_eq!(proto.file_id, original.file_id.to_string());
        assert_eq!(proto.path, "/test/file.txt");
        assert_eq!(proto.size, 1024);
        assert_eq!(proto.permissions, 0o644);

        // Convert back to domain type
        let converted: FileMetadata = (&proto).try_into().unwrap();
        assert_eq!(converted.file_id, original.file_id);
        assert_eq!(converted.path, original.path);
        assert_eq!(converted.size, original.size);
        assert_eq!(converted.permissions, original.permissions);
    }

    #[test]
    fn test_storage_location_conversion() {
        let original = StorageLocation::new(
            Uuid::new_v4(),
            "disk1".to_string(),
            PathBuf::from("/storage/chunks/abc123"),
        );

        // Convert to proto
        let proto: StorageLocationInfo = (&original).into();
        assert_eq!(proto.node_id, original.node_id.to_string());
        assert_eq!(proto.disk_id, "disk1");

        // Convert back
        let converted: StorageLocation = (&proto).try_into().unwrap();
        assert_eq!(converted.node_id, original.node_id);
        assert_eq!(converted.disk_id, original.disk_id);
        assert_eq!(converted.path, original.path);
    }

    #[test]
    fn test_event_creation() {
        let file_metadata = FileMetadata::new(PathBuf::from("/test.txt"), 100, 0o644);
        let peer_id = "peer123".to_string();
        let node_id = Uuid::new_v4();

        let event = create_file_created_event(1, peer_id.clone(), node_id, &file_metadata);

        assert_eq!(event.sequence_number, 1);
        assert!(event.version.is_some());
        assert!(event.originator.is_some());

        let originator = event.originator.unwrap();
        assert_eq!(originator.peer_id, peer_id);
        assert_eq!(originator.node_id, node_id.to_string());

        // Verify event type
        match event.event {
            Some(metadata_event::Event::FileCreated(file_created)) => {
                assert!(file_created.file.is_some());
            }
            _ => panic!("Expected FileCreated event"),
        }
    }

    #[test]
    fn test_invalid_uuid_error() {
        let bad_file_info = FileInfo {
            file_id: "not-a-uuid".to_string(),
            path: "/test".to_string(),
            size: 100,
            permissions: 0o644,
            created_at: 0,
            modified_at: 0,
            accessed_at: 0,
            stripe_count: 0,
            checksum: 0,
        };

        let result: Result<FileMetadata, _> = (&bad_file_info).try_into();
        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), ProtocolError::InvalidUuid(_)));
    }
}
